# chord_diagrams.py

CHORD_IMAGES = {
    'A': 'A.png', 'A6': 'A6.png', 'A7': 'A7.png', 'A9': 'A9.png', 'Aaug': 'Aaug.png',
    'Ab': 'Ab.png', 'Ab6': 'Ab6.png', 'Ab7': 'Ab7.png', 'Ab9': 'Ab9.png', 'Abaug': 'Abaug.png',
    'Abdim': 'Abdim.png', 'Abm': 'Abm.png', 'Abm6': 'Abm6.png', 'Abm7': 'Abm7.png', 'Abm7b5': 'Abm7b5.png',
    'Am': 'Am.png', 'Am6': 'Am6.png', 'Am7': 'Am7.png', 'Am7b5': 'Am7b5.png',
    'Amaj7': 'Amaj7.png', 'Aaug': 'Aaug.png',
    'B': 'B.png', 'B6': 'B6.png', 'B7': 'B7.png', 'B9': 'B9.png', 'Baug': 'Baug.png',
    'Bb': 'Bb.png', 'Bb6': 'Bb6.png', 'Bb7': 'Bb7.png', 'Bb9': 'Bb9.png', 'Bbaug': 'Bbaug.png',
    'Bbm': 'Bbm.png', 'Bbm6': 'Bbm6.png', 'Bbm7': 'Bbm7.png', 'Bbm7b5': 'Bbm7b5.png', 'Bbdim': 'Bbdim.png',
    'Bm': 'Bm.png', 'Bm6': 'Bm6.png', 'Bm7': 'Bm7.png', 'Bm7b5': 'Bm7b5.png',
    'C': 'C.png', 'C6': 'C6.png', 'C7': 'C7.png', 'C9': 'C9.png', 'Caug': 'Caug.png',
    'Cm': 'Cm.png', 'Cm6': 'Cm6.png', 'Cm7': 'Cm7.png', 'Cm7b5': 'Cm7b5.png',
    'Cmaj7': 'Cmaj7.png', 'Cdim': 'Cdim.png',
    'Db': 'Db.png', 'Db6': 'Db6.png', 'Db7': 'Db7.png', 'Db9': 'Db9.png', 'Dbaug': 'Dbaug.png',
    'Dbm': 'Dbm.png', 'Dbm6': 'Dbm6.png', 'Dbm7b5': 'Dbm7b5.png', 'Dbmaj7': 'Dbmaj7.png',
    'D': 'D.png', 'D6': 'D6.png', 'D7': 'D7.png', 'D9': 'D9.png', 'Daug': 'Daug.png',
    'Dm': 'Dm.png', 'Dm6': 'Dm6.png', 'Dm7': 'Dm7.png', 'Dm7b5': 'Dm7b5.png',
    'Dmaj7': 'Dmaj7.png', 'Ddim': 'Ddim.png', 'Dbdim': 'Dbdim.png', 'Dbm7': 'Dbm7.png',
    'E': 'E.png', 'E6': 'E6.png', 'E7': 'E7.png', 'E9': 'E9.png', 'Eaug': 'Eaug.png',
    'Em': 'Em.png', 'Em6': 'Em6.png', 'Em7': 'Em7.png', 'Em7b5': 'Em7b5.png', 'Emaj7': 'Emaj7.png',
    'Ebdim': 'Ebdim.png', 'Eb': 'Eb.png', 'Eb6': 'Eb6.png', 'Eb7': 'Eb7.png', 'Eb9': 'Eb9.png',
    'Ebaug': 'Ebaug.png', 'Ebsus': 'Ebsus.png', 'Ebsus': 'Ebsus.png', 'Ebm': 'Ebm.png',
    'F': 'F.png', 'F6': 'F6.png', 'F7': 'F7.png', 'F9': 'F9.png', 'Faug': 'Faug.png',
    'Fm': 'Fm.png', 'Fm6': 'Fm6.png', 'Fm7': 'Fm7.png', 'Fm7b5': 'Fm7b5.png', 'Fdim': 'Fdim.png',
    'Fmaj7': 'Fmaj7.png', 'Fdim': 'Fdim.png', 'G': 'G.png', 'G6': 'G6.png', 'G7': 'G7.png',
    'G9': 'G9.png', 'Gaug': 'Gaug.png', 'Gdim': 'Gdim.png', 'Gmaj7': 'Gmaj7.png', 'Gm': 'Gm.png',
    'Gm6': 'Gm6.png', 'Gm7': 'Gm7.png', 'Gm7b5': 'Gm7b5.png', 'Gbdim': 'Gbdim.png', 'Gbsus': 'Gbsus.png',
    'Gb': 'Gb.png', 'Gb6': 'Gb6.png', 'Gb7': 'Gb7.png', 'Gb9': 'Gb9.png', 'Gbaug': 'Gbaug.png',
    'Gbm': 'Gbm.png', 'Gbm6': 'Gbm6.png', 'Gbm7': 'Gbm7.png', 'Gbm7b5': 'Gbm7b5.png',
}
