scales = {
    'C': {
        'C_major': ['C', 'D', 'E', 'F', 'G', 'A', 'B'],
        'C_minor': ['C', 'D', 'Eb', 'F', 'G', 'Ab', 'Bb'],
        'C_ionian': ['C', 'D', 'E', 'F', 'G', 'A', 'B'],
        'C_dorian': ['C', 'D', 'Eb', 'F', 'G', 'A', 'Bb'],
        'C_phrygian': ['C', 'Db', 'Eb', 'F', 'G', 'Ab', 'Bb'],
        'C_lydian': ['C', 'D', 'E', 'F#', 'G', 'A', 'B'],
        'C_mixolydian': ['C', 'D', 'E', 'F', 'G', 'A', 'Bb'],
        'C_aolian': ['C', 'D', 'Eb', 'F', 'G', 'Ab', 'Bb'],
        'C_locrian': ['C', 'Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb'],
        'C_whole_tone': ['C', 'D', 'E', 'F#', 'G#', 'A#'],
        'C_hungarian_minor': ['C', 'D', 'Eb', 'F#', 'G', 'Ab', 'B'],
        'C_octatonic': ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G'],
        'C_arabic': ['C', 'Db', 'E', 'F', 'G', 'Ab', 'B'],
        'C_chinese': ['C', 'D', 'E', 'G', 'A'],
        'C_dodecaphonic': ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
        'C_rumba': ['C', 'D', 'Eb', 'F', 'G', 'Ab', 'Bb'],
        'C_raga_yo': ['C', 'D', 'E', 'F', 'G', 'A', 'B'],
        'C_raga_ka': ['C', 'D', 'E', 'F', 'G', 'A', 'B']
    },
    'C#': {
        'C#_major': ['C#', 'D#', 'E#', 'F#', 'G#', 'A#', 'B#'],
        'C#_minor': ['C#', 'D#', 'E', 'F#', 'G#', 'A', 'B'],
        'C#_ionian': ['C#', 'D#', 'E#', 'F#', 'G#', 'A#', 'B#'],
        'C#_dorian': ['C#', 'D#', 'E', 'F#', 'G#', 'A#', 'B'],
        'C#_phrygian': ['C#', 'D', 'E', 'F#', 'G#', 'A', 'B'],
        'C#_lydian': ['C#', 'D#', 'E#', 'G', 'A#', 'B#', 'C#'],
        'C#_mixolydian': ['C#', 'D#', 'E#', 'F#', 'G#', 'A', 'B'],
        'C#_aolian': ['C#', 'D#', 'E', 'F#', 'G#', 'A', 'B'],
        'C#_locrian': ['C#', 'D', 'E', 'F#', 'G', 'A', 'B'],
        'C#_whole_tone': ['C#', 'D#', 'E#', 'G', 'A', 'B'],
        'C#_hungarian_minor': ['C#', 'D#', 'E', 'G', 'A', 'B', 'C'],
        'C#_octatonic': ['C#', 'D', 'D#', 'E', 'F#', 'G', 'G#', 'A'],
        'C#_arabic': ['C#', 'D', 'E', 'F#', 'G#', 'A', 'B'],
        'C#_chinese': ['C#', 'D#', 'E#', 'G#', 'A#'],
        'C#_dodecaphonic': ['C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B', 'C'],
        'C#_rumba': ['C#', 'D#', 'E', 'F#', 'G#', 'A', 'B'],
        'C#_raga_d': ['C#', 'D#', 'E', 'F#', 'G#', 'A', 'B'],
        'C#_raga_c': ['C#', 'D#', 'E', 'F#', 'G#', 'A', 'B']
    },
    'D': {
        'D_major': ['D', 'E', 'F#', 'G', 'A', 'B', 'C#'],
        'D_minor': ['D', 'E', 'F', 'G', 'A', 'Bb', 'C'],
        'D_ionian': ['D', 'E', 'F#', 'G', 'A', 'B', 'C#'],
        'D_dorian': ['D', 'E', 'F', 'G', 'A', 'B', 'C'],
        'D_phrygian': ['D', 'Eb', 'F', 'G', 'A', 'Bb', 'C'],
        'D_lydian': ['D', 'E', 'F#', 'G#', 'A', 'B', 'C#'],
        'D_mixolydian': ['D', 'E', 'F#', 'G', 'A', 'B', 'C'],
        'D_aolian': ['D', 'E', 'F', 'G', 'A', 'Bb', 'C'],
        'D_locrian': ['D', 'Eb', 'F', 'G', 'Ab', 'Bb', 'C'],
        'D_whole_tone': ['D', 'E', 'F#', 'G#', 'A#', 'C'],
        'D_hungarian_minor': ['D', 'E', 'F', 'G#', 'A', 'Bb', 'C#'],
        'D_octatonic': ['D', 'D#', 'E', 'F', 'G', 'G#', 'A#', 'B'],
        'D_arabic': ['D', 'Eb', 'F#', 'G', 'A', 'Bb', 'C'],
        'D_chinese': ['D', 'E', 'F#', 'A', 'B'],
        'D_dodecaphonic': ['D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B', 'C', 'C#'],
        'D_rumba': ['D', 'E', 'F', 'G', 'A', 'Bb', 'C'],
        'D_raga_c': ['D', 'E', 'F#', 'G', 'A', 'B', 'C#']
    },
    'D#': {
        'D#_major': ['D#', 'E#', 'F', 'G#', 'A#', 'B#', 'C'],
        'D#_minor': ['D#', 'E#', 'F#', 'G#', 'A#', 'B', 'C#'],
        'D#_ionian': ['D#', 'E#', 'F', 'G#', 'A#', 'B#', 'C'],
        'D#_dorian': ['D#', 'E#', 'F#', 'G#', 'A#', 'B', 'C#'],
        'D#_phrygian': ['D#', 'E', 'F#', 'G#', 'A#', 'B', 'C#'],
        'D#_lydian': ['D#', 'E#', 'F', 'G', 'A#', 'B#', 'C'],
        'D#_mixolydian': ['D#', 'E#', 'F', 'G#', 'A#', 'B', 'C#'],
        'D#_aolian': ['D#', 'E#', 'F#', 'G#', 'A#', 'B', 'C#'],
        'D#_locrian': ['D#', 'E', 'F#', 'G#', 'A', 'B', 'C#'],
        'D#_whole_tone': ['D#', 'E#', 'F', 'G', 'A#', 'B#'],
        'D#_hungarian_minor': ['D#', 'E#', 'F#', 'G', 'A#', 'B', 'C#'],
        'D#_octatonic': ['D#', 'E', 'E#', 'F#', 'G', 'G#', 'A#', 'B'],
        'D#_arabic': ['D#', 'E', 'F#', 'G#', 'A#', 'B', 'C#'],
        'D#_chinese': ['D#', 'E#', 'F', 'G#', 'A#'],
        'D#_dodecaphonic': ['D#', 'E', 'E#', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B', 'C', 'C#'],
        'D#_rumba': ['D#', 'E#', 'F#', 'G#', 'A#', 'B', 'C#'],
        'D#_raga_d': ['D#', 'E#', 'F#', 'G#', 'A#', 'B', 'C#'],
        'D#_raga_c': ['D#', 'E#', 'F#', 'G#', 'A#', 'B', 'C#']
    },
    'E': {
        'E_major': ['E', 'F#', 'G#', 'A', 'B', 'C#', 'D#'],
        'E_minor': ['E', 'F#', 'G', 'A', 'B', 'C', 'D'],
        'E_ionian': ['E', 'F#', 'G#', 'A', 'B', 'C#', 'D#'],
        'E_dorian': ['E', 'F#', 'G', 'A', 'B', 'C#', 'D'],
        'E_phrygian': ['E', 'F', 'G', 'A', 'B', 'C', 'D'],
        'E_lydian': ['E', 'F#', 'G#', 'A#', 'B', 'C#', 'D#'],
        'E_mixolydian': ['E', 'F#', 'G#', 'A', 'B', 'C#', 'D'],
        'E_aolian': ['E', 'F#', 'G', 'A', 'B', 'C', 'D'],
        'E_locrian': ['E', 'F', 'G', 'A', 'Bb', 'C', 'D'],
        'E_whole_tone': ['E', 'F#', 'G#', 'A#', 'B#', 'C#'],
        'E_hungarian_minor': ['E', 'F#', 'G', 'A#', 'B', 'C', 'D#'],
        'E_octatonic': ['E', 'F', 'F#', 'G', 'G#', 'A', 'B', 'C'],
        'E_arabic': ['E', 'F', 'G#', 'A', 'B', 'C', 'D#'],
        'E_chinese': ['E', 'F#', 'G#', 'A', 'B'],
        'E_dodecaphonic': ['E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#'],
        'E_rumba': ['E', 'F#', 'G', 'A', 'B', 'C', 'D'],
        'E_raga_d': ['E', 'F#', 'G#', 'A', 'B', 'C#', 'D#'],
        'E_raga_c': ['E', 'F#', 'G#', 'A', 'B', 'C#', 'D#']
    },
    'F': {
        'F_major': ['F', 'G', 'A', 'Bb', 'C', 'D', 'E'],
        'F_minor': ['F', 'G', 'Ab', 'Bb', 'C', 'Db', 'Eb'],
        'F_ionian': ['F', 'G', 'A', 'Bb', 'C', 'D', 'E'],
        'F_dorian': ['F', 'G', 'Ab', 'Bb', 'C', 'D', 'Eb'],
        'F_phrygian': ['F', 'Gb', 'Ab', 'Bb', 'C', 'Db', 'Eb'],
        'F_lydian': ['F', 'G', 'A', 'B', 'C', 'D', 'E'],
        'F_mixolydian': ['F', 'G', 'A', 'Bb', 'C', 'D', 'Eb'],
        'F_aolian': ['F', 'G', 'Ab', 'Bb', 'C', 'Db', 'Eb'],
        'F_locrian': ['F', 'Gb', 'Ab', 'Bb', 'Cb', 'Db', 'Eb'],
        'F_whole_tone': ['F', 'G', 'A', 'B', 'C#', 'D#'],
        'F_hungarian_minor': ['F', 'G', 'Ab', 'B', 'C', 'Db', 'E'],
        'F_octatonic': ['F', 'F#', 'G#', 'A', 'B', 'C', 'C#', 'D'],
        'F_arabic': ['F', 'Gb', 'A', 'Bb', 'C', 'Db', 'E'],
        'F_chinese': ['F', 'G', 'A', 'C', 'D'],
        'F_dodecaphonic': ['F', 'F#', 'G', 'G#', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E'],
        'F_rumba': ['F', 'G', 'Ab', 'Bb', 'C', 'Db', 'Eb'],
        'F_raga_yo': ['F', 'G', 'A', 'Bb', 'C', 'D', 'E'],
        'F_raga_ka': ['F', 'G', 'A', 'Bb', 'C', 'D', 'E']
    },
    'F#': {
        'F#_major': ['F#', 'G#', 'A#', 'B', 'C#', 'D#', 'E#'],
        'F#_minor': ['F#', 'G#', 'A', 'B', 'C#', 'D', 'E'],
        'F#_ionian': ['F#', 'G#', 'A#', 'B', 'C#', 'D#', 'E#'],
        'F#_dorian': ['F#', 'G#', 'A', 'B', 'C#', 'D#', 'E'],
        'F#_phrygian': ['F#', 'G', 'A', 'B', 'C#', 'D', 'E'],
        'F#_lydian': ['F#', 'G#', 'A#', 'B#', 'C#', 'D#', 'E#'],
        'F#_mixolydian': ['F#', 'G#', 'A#', 'B', 'C#', 'D#', 'E'],
        'F#_aolian': ['F#', 'G#', 'A', 'B', 'C#', 'D', 'E'],
        'F#_locrian': ['F#', 'G', 'A', 'B', 'C', 'D', 'E'],
        'F#_whole_tone': ['F#', 'G#', 'A#', 'B#', 'C#', 'D#'],
        'F#_hungarian_minor': ['F#', 'G#', 'A', 'B#', 'C#', 'D', 'E#'],
        'F#_octatonic': ['F#', 'G', 'G#', 'A', 'B', 'C', 'C#', 'D'],
        'F#_arabic': ['F#', 'G', 'A#', 'B', 'C#', 'D', 'E'],
        'F#_chinese': ['F#', 'G#', 'A#', 'C#', 'D#'],
        'F#_dodecaphonic': ['F#', 'G', 'G#', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'E#'],
        'F#_rumba': ['F#', 'G#', 'A', 'B', 'C#', 'D', 'E'],
        'F#_raga_d': ['F#', 'G#', 'A', 'B', 'C#', 'D', 'E'],
        'F#_raga_c': ['F#', 'G#', 'A', 'B', 'C#', 'D', 'E']
    },
    'G': {
        'G_major': ['G', 'A', 'B', 'C', 'D', 'E', 'F#'],
        'G_minor': ['G', 'A', 'Bb', 'C', 'D', 'Eb', 'F'],
        'G_ionian': ['G', 'A', 'B', 'C', 'D', 'E', 'F#'],
        'G_dorian': ['G', 'A', 'Bb', 'C', 'D', 'E', 'F'],
        'G_phrygian': ['G', 'Ab', 'Bb', 'C', 'D', 'Eb', 'F'],
        'G_lydian': ['G', 'A', 'B', 'C#', 'D', 'E', 'F#'],
        'G_mixolydian': ['G', 'A', 'B', 'C', 'D', 'E', 'F'],
        'G_aolian': ['G', 'A', 'Bb', 'C', 'D', 'Eb', 'F'],
        'G_locrian': ['G', 'Ab', 'Bb', 'C', 'Db', 'Eb', 'F'],
        'G_whole_tone': ['G', 'A', 'B', 'C#', 'D#', 'E#'],
        'G_hungarian_minor': ['G', 'A', 'Bb', 'C#', 'D', 'Eb', 'F#'],
        'G_octatonic': ['G', 'G#', 'A', 'Bb', 'C', 'C#', 'D', 'Eb'],
        'G_arabic': ['G', 'Ab', 'B', 'C', 'D', 'Eb', 'F#'],
        'G_chinese': ['G', 'A', 'B', 'D', 'E'],
        'G_dodecaphonic': ['G', 'G#', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#'],
        'G_rumba': ['G', 'A', 'Bb', 'C', 'D', 'Eb', 'F'],
        'G_raga_yo': ['G', 'A', 'B', 'C', 'D', 'E', 'F#'],
        'G_raga_ka': ['G', 'A', 'B', 'C', 'D', 'E', 'F#']
    },
    'G#': {
        'G#_major': ['G#', 'A#', 'B#', 'C#', 'D#', 'E#', 'F'],
        'G#_minor': ['G#', 'A#', 'B', 'C#', 'D#', 'E', 'F#'],
        'G#_ionian': ['G#', 'A#', 'B#', 'C#', 'D#', 'E#', 'F'],
        'G#_dorian': ['G#', 'A#', 'B', 'C#', 'D#', 'E#', 'F#'],
        'G#_phrygian': ['G#', 'A', 'B', 'C#', 'D#', 'E', 'F#'],
        'G#_lydian': ['G#', 'A#', 'B#', 'C', 'D#', 'E#', 'F'],
        'G#_mixolydian': ['G#', 'A#', 'B#', 'C#', 'D#', 'E', 'F#'],
        'G#_aolian': ['G#', 'A#', 'B', 'C#', 'D#', 'E', 'F#'],
        'G#_locrian': ['G#', 'A', 'B', 'C#', 'D', 'E', 'F#'],
        'G#_whole_tone': ['G#', 'A#', 'B#', 'C', 'D', 'E#'],
        'G#_hungarian_minor': ['G#', 'A#', 'B', 'C', 'D#', 'E', 'F#'],
        'G#_octatonic': ['G#', 'A', 'A#', 'B', 'C#', 'D', 'D#', 'E'],
        'G#_arabic': ['G#', 'A', 'B#', 'C#', 'D#', 'E', 'F#'],
        'G#_chinese': ['G#', 'A#', 'B#', 'D#', 'E#'],
        'G#_dodecaphonic': ['G#', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'E#', 'F', 'F#'],
        'G#_rumba': ['G#', 'A#', 'B', 'C#', 'D#', 'E', 'F#'],
        'G#_raga_d': ['G#', 'A#', 'B', 'C#', 'D#', 'E', 'F#'],
        'G#_raga_c': ['G#', 'A#', 'B', 'C#', 'D#', 'E', 'F#']
    },
    'A': {
        'A_major': ['A', 'B', 'C#', 'D', 'E', 'F#', 'G#'],
        'A_minor': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
        'A_ionian': ['A', 'B', 'C#', 'D', 'E', 'F#', 'G#'],
        'A_dorian': ['A', 'B', 'C', 'D', 'E', 'F#', 'G'],
        'A_phrygian': ['A', 'Bb', 'C', 'D', 'E', 'F', 'G'],
        'A_lydian': ['A', 'B', 'C#', 'D#', 'E', 'F#', 'G#'],
        'A_mixolydian': ['A', 'B', 'C#', 'D', 'E', 'F#', 'G'],
        'A_aolian': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
        'A_locrian': ['A', 'Bb', 'C', 'D', 'Eb', 'F', 'G'],
        'A_whole_tone': ['A', 'B', 'C#', 'D#', 'E#', 'F#'],
        'A_hungarian_minor': ['A', 'B', 'C', 'D#', 'E', 'F', 'G#'],
        'A_octatonic': ['A', 'A#', 'B', 'C', 'D', 'D#', 'E', 'F'],
        'A_arabic': ['A', 'Bb', 'C#', 'D', 'E', 'F', 'G#'],
        'A_chinese': ['A', 'B', 'C#', 'E', 'F#'],
        'A_dodecaphonic': ['A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'],
        'A_rumba': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
        'A_raga_yo': ['A', 'B', 'C#', 'D', 'E', 'F#', 'G#'],
        'A_raga_ka': ['A', 'B', 'C#', 'D', 'E', 'F#', 'G#']
    },
    'A#': {
        'A#_major': ['A#', 'B#', 'C', 'D#', 'E#', 'F', 'G'],
        'A#_minor': ['A#', 'B#', 'C#', 'D#', 'E#', 'F#', 'G#'],
        'A#_ionian': ['A#', 'B#', 'C', 'D#', 'E#', 'F', 'G'],
        'A#_dorian': ['A#', 'B#', 'C#', 'D#', 'E#', 'F', 'G#'],
        'A#_phrygian': ['A#', 'C', 'C#', 'D#', 'E#', 'F#', 'G#'],
        'A#_lydian': ['A#', 'B#', 'C', 'D', 'E#', 'F', 'G'],
        'A#_mixolydian': ['A#', 'B#', 'C', 'D#', 'E#', 'F', 'G#'],
        'A#_aolian': ['A#', 'B#', 'C#', 'D#', 'E#', 'F#', 'G#'],
        'A#_locrian': ['A#', 'C', 'C#', 'D#', 'E', 'F#', 'G#'],
        'A#_whole_tone': ['A#', 'B#', 'C', 'D', 'E', 'F'],
        'A#_hungarian_minor': ['A#', 'B#', 'C#', 'D', 'E#', 'F#', 'G'],
        'A#_octatonic': ['A#', 'B', 'B#', 'C#', 'D#', 'E', 'E#', 'F#'],
        'A#_arabic': ['A#', 'C', 'C#', 'D#', 'E#', 'F#', 'G#'],
        'A#_chinese': ['A#', 'B#', 'C', 'D#', 'E#'],
        'A#_dodecaphonic': ['A#', 'B', 'B#', 'C', 'C#', 'D', 'D#', 'E', 'E#', 'F', 'F#', 'G#'],
        'A#_rumba': ['A#', 'B#', 'C#', 'D#', 'E#', 'F#', 'G#'],
        'A#_raga_d': ['A#', 'B#', 'C#', 'D#', 'E#', 'F#', 'G#'],
        'A#_raga_c': ['A#', 'B#', 'C#', 'D#', 'E#', 'F#', 'G#']
    },
    'B': {
        'B_major': ['B', 'C#', 'D#', 'E', 'F#', 'G#', 'A#'],
        'B_minor': ['B', 'C#', 'D', 'E', 'F#', 'G', 'A'],
        'B_ionian': ['B', 'C#', 'D#', 'E', 'F#', 'G#', 'A#'],
        'B_dorian': ['B', 'C#', 'D', 'E', 'F#', 'G#', 'A'],
        'B_phrygian': ['B', 'C', 'D', 'E', 'F#', 'G', 'A'],
        'B_lydian': ['B', 'C#', 'D#', 'E#', 'F#', 'G#', 'A#'],
        'B_mixolydian': ['B', 'C#', 'D#', 'E', 'F#', 'G#', 'A'],
        'B_aolian': ['B', 'C#', 'D', 'E', 'F#', 'G', 'A'],
        'B_locrian': ['B', 'C', 'D', 'E', 'F', 'G', 'A'],
        'B_whole_tone': ['B', 'C#', 'D#', 'E#', 'F', 'G'],
        'B_hungarian_minor': ['B', 'C#', 'D', 'E#', 'F#', 'G', 'A#'],
        'B_octatonic': ['B', 'C', 'C#', 'D', 'E', 'F', 'F#', 'G'],
        'B_arabic': ['B', 'C', 'D#', 'E', 'F#', 'G', 'A#'],
        'B_chinese': ['B', 'C#', 'D#', 'F#', 'G#'],
        'B_dodecaphonic': ['B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#'],
        'B_rumba': ['B', 'C#', 'D', 'E', 'F#', 'G', 'A'],
        'B_raga_d': ['B', 'C#', 'D#', 'E', 'F#', 'G#', 'A#'],
        'B_raga_c': ['B', 'C#', 'D#', 'E', 'F#', 'G#', 'A#']
    }
}
